language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "ramyamanuru-github"
    token:
      secure: "ff4e6a7c01e6ea98da22226fddc64a73005568dd"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'